org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=128m
android.useAndroidX=true
android.enableJetifier=false
rive.native.skipSetup=false # Set to true to skip the rive_native setup, manually run `dart run rive_native:setup --verbose --clean --platform android` to setup the native libraries
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
